# Generated by Django 4.2.1 on 2023-06-28 17:28

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0003_rename_oder_order_rename_oderitem_orderitem_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cusstomer',
            new_name='Customer',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='cusstomer',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='cusstomer',
            new_name='customer',
        ),
    ]
